export const transactionTableDummyData = [
    {
      date: "October 26, 2022",
      description: "lorem ipsum",
      amount: 0.1,
      currencyType: "ETH",
      transactionType: "Debit",
    },
    {
      date: "September 7, 2022",
      description: "lorem ipsum",
      amount: 1.1,
      currencyType: "ETH",
      transactionType: "Debit",
    },
    {
      date: "December 9, 2022",
      description: "lorem ipsum",
      amount: 0.15,
      currencyType: "ETH",
      transactionType: "Credit",
    },
    {
      date: "October 13, 2022",
      description: "lorem ipsum",
      amount: 11936,
      currencyType: "USDC",
      transactionType: "Debit",
    },
    {
      date: "June 23, 2022",
      description: "lorem ipsum",
      amount: 5000,
      currencyType: "USDC",
      transactionType: "Credit",
    },
    {
      date: "November 9, 2022",
      description: "lorem ipsum",
      amount: 0.15,
      currencyType: "ETH",
      transactionType: "Credit",
    },
    {
      date: "January 19, 2022",
      description: "lorem ipsum",
      amount: 0.5,
      currencyType: "ETH",
      transactionType: "Debit",
    },
    {
      date: "July 4, 2022",
      description: "lorem ipsum",
      amount: 1.12,
      currencyType: "ETH",
      transactionType: "Debit",
    },
    {
      date: "December 5, 2022",
      description: "lorem ipsum",
      amount: 0.15,
      currencyType: "ETH",
      transactionType: "Credit",
    },
    {
      date: "March 17, 2022",
      description: "lorem ipsum",
      amount: 0.1,
      currencyType: "ETH",
      transactionType: "Debit",
    },
    {
      date: "September 25, 2022",
      description: "lorem ipsum",
      amount: 1.7,
      currencyType: "ETH",
      transactionType: "Debit",
    },
    {
      date: "May 2, 2022",
      description: "lorem ipsum",
      amount: 0.18,
      currencyType: "ETH",
      transactionType: "Credit",
    },
  ];